import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Searchbar from "@/components/searchbar/page";
import { ReduxProvider } from "@/store/provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Searchbar helperText="Preparate un cafe" />

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
